In [5]:
import torch
import torch.nn as nn
!pip install transformers
from transformers.optimization import Adafactor
import torch.optim as opt

In [6]:
a = torch.randn(32, 100, 1)  
m = nn.Conv1d(100, 100, 1) 


# optimizer = Adafactor(m.parameters(), lr= 1e-3, relative_step=False)
optimizer = opt.Adam(m.parameters(), lr= 1e-3)

In [7]:
out = (m(a) ** 2).sum()
out.backward()
optimizer.step()

In [1]:
import torch

In [6]:
A =torch.nn.Conv1d(10, 10, 3, groups=10)

In [7]:
A.weight.size()

torch.Size([10, 1, 3])

In [1]:
import torch


In [6]:
torch.tensor([1,0,1,0,0,1]).view(3,2) + torch.arange(3).unsqueeze(-1) * 2

tensor([[1, 0],
        [3, 2],
        [4, 5]])

In [5]:
torch.arange(3).unsqueeze(-1) * 2

tensor([[0],
        [2],
        [4]])

In [7]:
torch.arange(3).argsort()

tensor([0, 1, 2])